// GENERATED by scripts/build_games.py from data/games.json — do not edit by hand.

package relay

// gameAutoQuery is how a server on query protocol "auto" is queried when its
// game is listed here; any other game uses A2S if its RCON protocol is
// "source" and no public query otherwise (EffectivePublicQueryProtocol).
var gameAutoQuery = map[string]string{
	"ARK: Survival Ascended": "disabled",
	"Arma 2":                 "a2s",
	"Arma 3":                 "a2s",
	"Arma Reforger":          "a2s",
	"DayZ":                   "a2s",
	"Minecraft":              "minecraft",
	"Rust":                   "a2s",
}
