<?php
// GENERATED by scripts/build_games.py from data/games.json — do not edit by hand.

// The games the API accepts and how Nitrado's game names map onto them.
// [label, rcon protocol, lower-case aliases]
const NICON_GAME_CATALOG = [
    ['7 Days to Die', 'telnet', ['7 days to die', '7dtd', 'seven days to die']],
    ['83', 'source', ['83']],
    ['ARK: Survival Ascended', 'source', ['ark: survival ascended', 'ark survival ascended', 'arksa']],
    ['ARK: Survival Evolved', 'source', ['ark: survival evolved', 'ark survival evolved', 'arkse']],
    ['Arma 2', 'battleye', ['arma 2', 'arma2']],
    ['Arma 3', 'battleye', ['arma 3', 'arma3']],
    ['Arma Reforger', 'battleye', ['arma reforger', 'reforger']],
    ['ATLAS', 'source', ['atlas']],
    ['BattleBit Remastered', 'battlebit', ['battlebit remastered', 'battlebit']],
    ['Beyond the Wire', 'source', ['beyond the wire']],
    ['Conan Exiles', 'source', ['conan exiles']],
    ['Counter-Strike 2', 'source', ['counter-strike 2', 'counter strike 2', 'cs2']],
    ['Dark and Light', 'source', ['dark and light']],
    ['DayZ', 'battleye', ['dayz', 'day z']],
    ['Garry\'s Mod', 'source', ['garry\'s mod', 'garrys mod', 'gmod']],
    ['Hell Let Loose', 'source', ['hell let loose']],
    ['Hell Let Loose: Vietnam', 'source', ['hell let loose: vietnam', 'hell let loose vietnam']],
    ['Insurgency', 'source', ['insurgency']],
    ['Minecraft', 'source', ['minecraft']],
    ['MORDHAU', 'source', ['mordhau']],
    ['Palworld', 'palworld_rest', ['palworld']],
    ['Project Zomboid', 'source', ['project zomboid']],
    ['Rising Storm 2: Vietnam', 'source', ['rising storm 2', 'rising storm ii']],
    ['Rust', 'webrcon', ['rust']],
    ['Soulmask', 'source', ['soulmask']],
    ['Squad', 'source', ['squad']],
    ['Squad 44', 'source', ['squad 44', 'post scriptum']],
    ['V Rising', 'source', ['v rising', 'vrising']],
    ['Valheim', 'source', ['valheim']],
    ['WARDOGS', 'source', ['wardogs', 'war dogs']],
];
