<?php
// GENERATED by scripts/build_schema.py — do not edit.
// The newest migration in internal/store/migrations/; GET /readyz reports
// whether the database has it.
declare(strict_types=1);

const NICON_EXPECTED_SCHEMA_VERSION = 1;
