#!/usr/bin/env python3
"""Builds the files that are derived from the numbered migrations.

The single source of truth for the database schema is
internal/store/migrations/NNNN_name.sql. The Go relay applies them itself when
it starts. The PHP API's hosting usually has no such runner (a shared webspace
and phpMyAdmin), so two files are generated for it:

  webspace/schema.sql           every migration in order, each followed by the
                                INSERT that records it in schema_migrations —
                                run the whole file by hand after an update
  webspace/lib/schema_version.php   the newest version number, which the API's
                                /readyz compares with the database

    python3 scripts/build_schema.py          rewrite both files
    python3 scripts/build_schema.py --check  exit 1 if they are out of date (CI)
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MIGRATIONS = ROOT / "internal" / "store" / "migrations"
SCHEMA_SQL = ROOT / "webspace" / "schema.sql"
VERSION_PHP = ROOT / "webspace" / "lib" / "schema_version.php"

NAME = re.compile(r"^(\d{4})_([a-z0-9_]+)\.sql$")

TRACKING_TABLE = """CREATE TABLE IF NOT EXISTS schema_migrations (
	version INT UNSIGNED PRIMARY KEY,
	name VARCHAR(128) NOT NULL,
	applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

HEADER = """-- GENERATED by scripts/build_schema.py from internal/store/migrations/ —
-- do not edit this file; add a numbered migration there instead.
--
-- Run this whole file (phpMyAdmin / your host's SQL console) after deploying a
-- version of NiCon that changes the database. It is safe to run any number of
-- times, in any state: every statement is idempotent, and the migrations the
-- database already has are simply replayed. The Go relay applies the very same
-- migrations by itself when it starts, so if the relay runs against this
-- database you rarely need to; the PHP-only Cloud API never does. GET /readyz
-- on the API tells you whether this file is up to date.

"""


def migrations():
    found = []
    for path in sorted(MIGRATIONS.glob("*.sql")):
        match = NAME.match(path.name)
        if not match:
            sys.exit(f"{path.name}: migration files must be named NNNN_name.sql (lowercase, digits, underscores)")
        found.append((int(match.group(1)), match.group(2), path.read_text()))
    if not found:
        sys.exit("no migrations found")
    for expected, (version, _, _) in enumerate(found, start=1):
        if version != expected:
            sys.exit(f"migration versions must be contiguous from 0001: expected {expected:04d}, found {version:04d}")
    return found


def build():
    found = migrations()
    sql = [HEADER, TRACKING_TABLE]
    for version, name, text in found:
        sql.append(f"\n-- ===== migration {version:04d}: {name} =====\n\n")
        sql.append(text.rstrip("\n") + "\n\n")
        sql.append(f"INSERT IGNORE INTO schema_migrations (version, name) VALUES ({version}, '{name}');\n")
    php = f"""<?php
// GENERATED by scripts/build_schema.py — do not edit.
// The newest migration in internal/store/migrations/; GET /readyz reports
// whether the database has it.
declare(strict_types=1);

const NICON_EXPECTED_SCHEMA_VERSION = {found[-1][0]};
"""
    return {SCHEMA_SQL: "".join(sql), VERSION_PHP: php}


def main():
    outputs = build()
    if "--check" in sys.argv[1:]:
        stale = [str(path.relative_to(ROOT)) for path, text in outputs.items() if not path.exists() or path.read_text() != text]
        if stale:
            sys.exit("out of date (run python3 scripts/build_schema.py): " + ", ".join(stale))
        print("schema files are up to date")
        return
    for path, text in outputs.items():
        path.write_text(text)
        print("wrote", path.relative_to(ROOT))


if __name__ == "__main__":
    main()
