#!/usr/bin/env python3
"""Generate the per-language game catalogs from data/games.json.

data/games.json is the one place that says which games NiCon supports: the
label stored in servers.game, the RCON protocol a game normally uses, how
"auto" resolves the public query, whether it is verified against a real
server, how it is integrated, and the names Nitrado/the UI match it by.

Generated (never edit by hand; CI runs this with --check):
  docs/games-catalog.js              the browser's catalog (game selects, protocol
                                     suggestions, name matching, welcome page)
  webspace/lib/games_catalog.php     the Cloud API's allowlist + Nitrado matching
  internal/relay/games_catalog.go    the relay's "auto" public-query decision

The per-game parsers and artwork stay in docs/games.js; a browser test checks
that both sides describe the same set of games.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data" / "games.json"

PROTOCOLS = {"source", "webrcon", "battleye", "telnet", "battlebit", "palworld_rest"}
AUTO_QUERY = {"a2s", "minecraft", "disabled"}
INTEGRATIONS = {"native", "protocol", "provisional", "mod"}

HEADER = "GENERATED by scripts/build_games.py from data/games.json — do not edit by hand."


def load():
    games = json.loads(SOURCE.read_text(encoding="utf-8"))["games"]
    keys, labels = set(), set()
    for g in games:
        for field in ("key", "label", "protocol", "tested", "integration", "aliases"):
            if field not in g:
                sys.exit(f"{g.get('key', '?')}: missing {field}")
        if g["key"] in keys or g["label"] in labels:
            sys.exit(f"duplicate game {g['key']!r}")
        keys.add(g["key"])
        labels.add(g["label"])
        if g["protocol"] not in PROTOCOLS:
            sys.exit(f"{g['key']}: unknown protocol {g['protocol']!r}")
        if g.get("autoQuery", "a2s") not in AUTO_QUERY:
            sys.exit(f"{g['key']}: unknown autoQuery {g['autoQuery']!r}")
        if g["integration"] not in INTEGRATIONS:
            sys.exit(f"{g['key']}: unknown integration {g['integration']!r}")
        if not g["aliases"] or any(a != a.lower() for a in g["aliases"]):
            sys.exit(f"{g['key']}: aliases must be non-empty and lower-case")
    return games


def js(games):
    body = json.dumps(games, indent=2, ensure_ascii=False)
    return f"// {HEADER}\nwindow.NICON_GAME_CATALOG = {body};\n"


def php_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def php(games):
    lines = [
        "<?php",
        f"// {HEADER}",
        "",
        "// The games the API accepts and how Nitrado's game names map onto them.",
        "// [label, rcon protocol, lower-case aliases]",
        "const NICON_GAME_CATALOG = [",
    ]
    for g in games:
        aliases = ", ".join(php_str(a) for a in g["aliases"])
        lines.append(f"    [{php_str(g['label'])}, {php_str(g['protocol'])}, [{aliases}]],")
    lines += ["];", ""]
    return "\n".join(lines)


def go(games):
    lines = [
        f"// {HEADER}",
        "",
        "package relay",
        "",
        "// gameAutoQuery is how a server on query protocol \"auto\" is queried when its",
        "// game is listed here; any other game uses A2S if its RCON protocol is",
        "// \"source\" and no public query otherwise (EffectivePublicQueryProtocol).",
        "var gameAutoQuery = map[string]string{",
    ]
    # Aligned the way gofmt aligns map values, so the file is gofmt-clean.
    entries = [(json.dumps(g["label"]) + ":", json.dumps(g["autoQuery"]) + ",") for g in games if "autoQuery" in g]
    width = max(len(k) for k, _ in entries)
    for key, value in entries:
        lines.append(f"\t{key.ljust(width)} {value}")
    lines += ["}", ""]
    return "\n".join(lines)


def main():
    games = load()
    outputs = {
        ROOT / "docs" / "games-catalog.js": js(games),
        ROOT / "webspace" / "lib" / "games_catalog.php": php(games),
        ROOT / "internal" / "relay" / "games_catalog.go": go(games),
    }
    if "--check" in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, text in outputs.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != text]
        if stale:
            sys.exit("out of date, run `python3 scripts/build_games.py`: " + ", ".join(stale))
        return
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
        print("wrote", path.relative_to(ROOT))


if __name__ == "__main__":
    main()
